name: "Running tests: ruff stylinh"

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Style, mypy, pytest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Install poetry
      run: pip install poetry==1.7.1
    - name: Install Dependencies
      run: poetry install
    - name: Check style
      run: poetry run ruff check . && poetry run ruff format --check .
